### ISSUE TITLE
Add support for core's term meta and deprecate FM term meta

### ISSUE THREAD

**Issue by mboynes** [alleyinteractive/wordpress-fieldmanager#400]
As of WordPress 4.4, term meta is built into core. Fieldmanager has always provided an avenue for term meta by creating hidden posts 1:1 with terms, and using post meta to store the data. Fieldmanager's term meta should be deprecated, and support should be added for core's term meta.

This is a delicate situation, as we don't want to break backwards compatibility, but we also don't want the default to be a deprecated (and highly discouraged) option. In order to accomplish this, we're going to deprecate the current helper method `Fieldmanager_Field::add_term_form()` in favor of a new method `Fieldmanager_Field::add_term_meta_box()`, and we're going to deprecate the current argument order for `Fieldmanager_Context_Term::__construct()` to prefer arguments passed as an array instead of being passed separately. The default for the deprecated method and construct arguments will be to use Fieldmanager's term meta, and the default for the new method and construct argument array will be to use core's term meta.

* [x] Deprecate `Fieldmanager_Field::add_term_form()`, ensuring that the default term meta storage remains Fieldmanager's term meta.
* [x] Add `Fieldmanager_Field::add_term_meta_box()` which sets the default term meta storage to be core's.
* [x] Deprecate the individual arguments passed to `Fieldmanager_Context_Term::__construct()`, ensuring that the default term meta storage remains Fieldmanager's term meta.
* [x] Add support for arguments passed to `Fieldmanager_Context_Term::__construct()` as an array. The default term meta storage should be core's when creating the object this way (however, it should be able to be overridden).
* [x] Ensure that existing test coverage for Fieldmanager term meta remain intact.
* [ ] Add full test coverage for using core term meta.
* [x] Build a migration tool to move all Fieldmanager term meta to core term meta. This should be a separate plugin.

**Comment by mboynes** [comment]
See https://github.com/alleyinteractive/fieldmanager-term-meta-migration for the migration tool.
