### ISSUE TITLE
1.2.0 and 1.3.0 Planning Meeting

### ISSUE THREAD

**Issue by mboynes** [alleyinteractive/wordpress-fieldmanager#648]
## TODO

- [ ] Deprecate `Fieldmanager_Context_Page`, `Fieldmanager_Draggable_Posts`
    - [ ] Afterwards, merge #573 
    - [ ] Reply to #566 to indicate that it's deprecated
- [ ] Ask @montchr to kick the tires on #157 
- [ ] @dlh01 to update minimum required WP version to 4.7
- [ ] Close #396
- [ ] Consider options for #503
- [ ] Close #438
